name:                wsb-args
version:             0.1.0.0
github:              githubuser/wsb-args
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:
# description:
# category:            Web

dependencies:
- base >= 4.7 && < 5
- text
- base64-bytestring
- bytestring
- memory
- cryptonite
- mtl
- case-insensitive
- bytestring-conversion
- wsb-counter-version

library:
  source-dirs: src
